config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|pt-BR/ do
    get '/auth/spotify/callback', to: 'home#spotify'
    get '/home/playlist', to: 'home#playlist'
    get '/home/spotify'

    root :to => "home#index"
  end

  resources :language do
    post :set_pt, :on => :collection
    post :set_en, :on => :collection
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action do
    I18n.locale = params[:locale] || session[:language] || extract_locale_from_accept_language_header
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def extract_locale_from_accept_language_header
    case request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
    when 'en'
      'en'
    when 'pt'
      'pt-BR'
    when 'pt-BR'
      'pt-BR'
    else
      'en'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :init_lastfm
  @spotify_user

  def index
  end

  def spotify
    @spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
    # Now you can access user's private data, create playlists and much more

    # Access private data
    @spotify_user.country #=> "US"
    @spotify_user.email   #=> "example@email.com"
  end

  def playlist
    case params[:color_selected]
    when "#58EC00" #Verde
      find_playlist LastFM::Tag.get_top_tracks(:tag => green_tag, :limit => 3)
    when "#0087EC" #Azul
      find_playlist LastFM::Tag.get_top_tracks(:tag => blue_tag)
    when "#CC0000" #Vermelho
      find_playlist LastFM::Tag.get_top_tracks(:tag => red_tag, :limit => 3)
    when "#FF5A00" #Laranja
      find_playlist LastFM::Tag.get_top_tracks(:tag => orange_tag, :limit => 3)
    else
      find_playlist LastFM::Tag.get_top_tracks(:tag => "animated", :limit => 3)
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def find_playlist (songs)
    position = Random.rand(2)
    song = ""
    songs["tracks"]["track"].each_with_index do |track, index|
      if index == position
        song = track["name"]
      end
    end
    @playlist =  RSpotify::Playlist.search(song)[Random.rand(5)]

  end

  def init_lastfm
    LastFM.api_key = "02012619a31a311a97f7d0fe6c3c50ad"
    LastFM.client_name = "Coolor"
  end

  def green_tag
    array = ["Calm", "Pacific"]
    array[Random.rand(1)]
  end

  def blue_tag
    array = ["Trust", "Sure"]
    array[Random.rand(1)]
  end

  def red_tag
    array = ["Love", "Revenge"]
    array[Random.rand(1)]
  end

  def orange_tag
    array = ["Happy", "Celebrate"]
    array[Random.rand(1)]
  end

end

app/controllers/language_controller.rb
class LanguageController < ActionController::Base


  def set_pt
    session[:language] = "pt-BR"
    redirect
  end

  def set_en
    session[:language] = "en"
    redirect
  end
end

private

def redirect
  redirect_to root_path
end

app/helpers/application_helper.rb
module ApplicationHelper

  def language_name
    case session[:language]
    when 'en'
      t("infos.ingles")
    when 'pt-BR'
      t("infos.portuges")
    else
      ' '
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_info.html.erb
<%= modal_dialog :id => "info_modal",
         :header => { :show_close => true, :dismiss => 'modal', :title => t('infos.modal_title') },
         :body   => { :content => t('texts.help')},
         :footer => {} %>
<script type="text/javascript">
  $('#info_modal').modal()
</script>

app/views/home/_navbar.html.erb
<%= nav_bar :static => :top, :brand => "", :responsive => true do %>
  <%= menu_group :pull => :right do %>
    <%= drop_down fa_icon("globe") do %>
      <%= menu_item fa_icon("flag", text: t("infos.portuges")), set_pt_language_index_path, method: :post %>
      <%= menu_item fa_icon("flag", text: t("infos.ingles")), set_en_language_index_path, method: :post %>
    <% end %>
  <% end %>
<% end %>

app/views/home/_player.html.erb
<iframe id="player" src=<%= "https://embed.spotify.com/?uri="+ playlist.uri %> width="200" height="300" frameborder="0" allowtransparency="true" class="btn-block"></iframe>

app/views/home/index.html.erb
<header>
  <div id="header-wrap">
    <%= render 'navbar'%>
  </div>
</header>
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <div class="inner cover">
        <h1 class="cover-heading">Coolor</h1>
        <p class="lead"><%= t('texts.sobre')%></p>
        <p class="lead">
          <%= link_to (fa_icon "", text: t('links.log_in'), class: "fa-2x") , '/auth/spotify', class: 'btn btn-lg btn-success btn-spotify' %>
        </p>
      </div>
      <footer class="mastfoot">
        <div class="inner">
          <p><%= t('links.desenvolvido_por')%> <a href="https://twitter.com/jonjts"  target="_blank">@jonjts</a></p>
        </div>
      </footer>
    </div>
  </div>
</div>

app/views/home/playlist.js.erb
$("#player").remove();

$("#div_player").append("<%= escape_javascript(render partial: 'player', locals: { playlist: @playlist } ) %>");  

app/views/home/spotify.html.erb
<header>
  <%= nav_bar :static => :top do %>
    <%= menu_group :pull => :right do %>
      <div class="pull-right user_padding">
        <%= @spotify_user.display_name + "  " %>
        <%= image_tag(@spotify_user.images[0].url, class: "user_img" ) %>
      </div>
    <% end %>
  <% end %>
</header>
<div class="container">
  <div class="row" style="text-align: center;padding-bottom: 67px;">
    <div class="col-xs-12" style="padding-bottom: 10px;">
    </div>
    <%= form_tag(home_playlist_path, method: "get", remote: true, format: :js) do %>
      <%= hidden_field_tag("color_selected", "") %>
      <%= submit_tag("", class: 'btn btn-lg btn-default  circle', id: "the_color") %>
    <% end %>
    <br>
    <div id="div_player" class="col-md-12 "  >
    </div>
  </div>
</div>
<%= render 'info'%>
<footer class="mastfoot">
  <div class="inner">
    <p><%= t('links.desenvolvido_por')%> <a href="https://twitter.com/jonjts"  target="_blank">@jonjts</a></p>
  </div>
</footer>
<script type="text/javascript">
  $(document).ready(function() {
                              var animate_loop, colors, i;
                              colors = ['#58EC00', '#0087EC', '#CC0000', '#FF5A00'];
                              i = 0;
                              animate_loop = function() {
                                $('.btn').addClass('magictime vanishIn');
                                var c = colors[i++ % colors.length];
                                $('#color_selected').val(c);
                                $('#the_color').animate({
                                  backgroundColor: c}, 3000, function() {
                                    animate_loop();
                                  });
                              };
                              animate_loop();
                            });
                             document.addEventListener("turbolinks:load", function() {
  
                             });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coolor (SNAPSHOT)</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="theme-color" content="#008966">
    <meta name="description" content="<%= t('texts.sobre')%>">
    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="#008966">
  </head>
  <body>
    <%= yield %>
  </body>
</html>